application: webfinger-unofficial
version: 1
runtime: python27
threadsafe: false
api_version: 1
default_expiration: 1d

handlers:
- url: /static
  static_dir: static

- url: /.well-known/host-meta
  script: app.py
  secure: always

- url: /user
  script: app.py
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
